# Generated by Django 5.1.5 on 2025-09-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, default='Bangladesh', null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='users.useraddress'),
        ),
    ]
