# Generated by Django 5.1.5 on 2025-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flower_discount_flower_isnew_flower_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
